import torch

#DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
DEVICE = "cpu"
RAW_DATA_SIZE_CAP = 10000
MLFLOW_URI = "http://127.0.0.1:5000"
MLFLOW_EXPERIMENT_NAME = "/GVAE_Full_Run"



# TRAINING HYPERPARAMETERS
NUM_EPOCH = 100
KL_BETA = 0.01
LEARNING_RATE = 0.01
BATCH_SIZE = 32

# GVAE MODEL HYPERPARAMETERS
ENCODER_EMBEDDING_SIZE = 32
LATENT_EMBEDDING_SIZE = 16
DECODER_SIZE = 128
EDGE_DIM = 11
NO_HEADS = 3
NUM_ENCODER_LAYERS = 3
NUM_DECODER_LAYERS = 3